// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWkYEVh2UPdiGhMruyVrdPzm3rUoKaoAM',
    appId: '1:305481454019:web:9c6b0c245d08ee755e6d76',
    messagingSenderId: '305481454019',
    projectId: 'momo-3f59c',
    authDomain: 'momo-3f59c.firebaseapp.com',
    storageBucket: 'momo-3f59c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG9IhevjwWniE6gbBwhNbnsIj9mclX8zg',
    appId: '1:305481454019:android:bbc3427cf18ad2785e6d76',
    messagingSenderId: '305481454019',
    projectId: 'momo-3f59c',
    storageBucket: 'momo-3f59c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc7dyuDIUPTjHr41iE2niDV3iM-zTWcS0',
    appId: '1:305481454019:ios:5579d58ceb83fc865e6d76',
    messagingSenderId: '305481454019',
    projectId: 'momo-3f59c',
    storageBucket: 'momo-3f59c.appspot.com',
    iosClientId: '305481454019-lcadicuhj8ei0ldcd4ri15gj5t8gi108.apps.googleusercontent.com',
    iosBundleId: 'com.example.momoMessagner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc7dyuDIUPTjHr41iE2niDV3iM-zTWcS0',
    appId: '1:305481454019:ios:ec0ea620aef40e775e6d76',
    messagingSenderId: '305481454019',
    projectId: 'momo-3f59c',
    storageBucket: 'momo-3f59c.appspot.com',
    iosClientId: '305481454019-cnnpt6kqvq82b3pqqjvtobbb3585c923.apps.googleusercontent.com',
    iosBundleId: 'com.example.momoMessagner.RunnerTests',
  );
}
